# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Maximum 120 characters', max_length=120, unique=True, verbose_name='Category|name')),
                ('slug', models.SlugField(help_text='Automatically generated from the title', unique=True)),
                ('order_index', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Direction|text')),
                ('order', positions.fields.PositionField(blank=True, default=-1, null=True)),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Food|name')),
                ('name_sorted', models.CharField(default='', max_length=150, verbose_name='Food|name_sorted')),
                ('conversion_factor', models.FloatField(blank=True, null=True)),
                ('name_plural', models.CharField(blank=True, max_length=150, null=True)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
                'ordering': ['name_sorted'],
            },
        ),
        migrations.CreateModel(
            name='FoodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='FoodGroup|name')),
            ],
            options={
                'verbose_name': 'FoodGroup',
                'verbose_name_plural': 'FoodGroups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Ingredient|amount')),
                ('amountMax', models.FloatField(blank=True, null=True)),
                ('order_index', positions.fields.PositionField(blank=True, default=-1, null=True)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.Direction')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Food')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ['direction', 'order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200, verbose_name='Photo|caption')),
                ('image', models.ImageField(upload_to='images')),
                ('keep', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='PrepMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, verbose_name='PrepMethod|name')),
            ],
            options={
                'verbose_name': 'Preparation Method',
                'verbose_name_plural': 'Preparation Methods',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Recipe|title')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='Recipe|summary')),
                ('description', models.TextField(blank=True, verbose_name='Recipe|description')),
                ('slug', models.SlugField(unique=True)),
                ('prep_time', models.CharField(blank=True, max_length=100)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('serving_value', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Category')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipies',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ServingString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='ServingString|text')),
            ],
            options={
                'verbose_name': 'Serving String',
                'verbose_name_plural': 'Serving Strings',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Source|name')),
                ('url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Unit|name')),
                ('name_abbrev', models.CharField(blank=True, max_length=60, verbose_name='Unit|name_abbrev')),
                ('plural_abbrev', models.CharField(blank=True, max_length=60, verbose_name='Unit|plural_abbrev')),
                ('type', models.IntegerField(choices=[(0, 'Other'), (1, 'Mass'), (2, 'Volume')])),
                ('system', models.IntegerField(choices=[(0, 'SI'), (1, 'Imperial')], null=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='serving_string',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.ServingString'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sources',
            field=models.ManyToManyField(blank=True, to='recipes.Source'),
        ),
        migrations.AddField(
            model_name='photo',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='prep_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.PrepMethod'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Unit'),
        ),
        migrations.AddField(
            model_name='food',
            name='conversion_src_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recipes.Unit'),
        ),
        migrations.AddField(
            model_name='food',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.FoodGroup'),
        ),
        migrations.AddField(
            model_name='direction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='recipes.Recipe'),
        ),
    ]
