# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20170509_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='conversion_factor',
        ),
        migrations.RemoveField(
            model_name='food',
            name='conversion_src_unit',
        ),
    ]
