# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amountMax',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='prep_method',
        ),
    ]
