# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_delete_prepmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='serving_string',
        ),
        migrations.DeleteModel(
            name='ServingString',
        ),
    ]
